### ISSUE TITLE
<div id="motto">Yidadaa</div> Yidadaa在那修改呀！

### ISSUE THREAD

**Issue by xiamuguizhi** [Yidadaa/Issue-Blog#2]
Yidadaa  应该不是bug吧  因为我找不到修改的地方. 或者是是自动github用户名吗？

**Comment by xiamuguizhi** [comment]
build.js  找到了 这个要自己修改..  6330行

**Comment by xiamuguizhi** [comment]
尝试在腾讯云cos 搭建这个博客尝试多次 失败

现在换了 存在 七牛云 Dome http://blog.9i3.cn/

**Comment by Yidadaa** [comment]
在配置项里加了个 window.motto 配置项，现在可以不用改dist.js了哈
