### ISSUE TITLE
如何设置client

### ISSUE THREAD

**Issue by xmdhs** [Yidadaa/Issue-Blog#6]
看http://blog.simplenaive.cn/Issue-Blog/dist/build.js 里似乎

`https://github.com/login/oauth/authorize?client_id="+a+"&client_secret="+s+"&redirect_uri={url}&scope=public_repo` 可以设置

但是还有一个 `https://api.github.com/repos/"+i+"/"+o+"/` 不知道该怎么设置

直接添加?client_id=似乎不行

毕竟一小时60次根本不够用

-----

还是不行 望解决

**Comment by Yidadaa** [comment]
@xmdhs 
Sorry，之前在忙毕设，一直没时间看issue。
目前还是用的公用接口，没有做授权，我这两天找时间加上。

还有，看源码的时候，可以从项目里的各种`.js`和`.vue`文件下手哈，`build.js`文件是自动编译出来的，看起来会很困难。

**Comment by Yidadaa** [comment]
引入了一个授权方案，但是存在隐私风险，晚些时候修复。

**Comment by xmdhs** [comment]
还是有点小问题

![IMG_1203.PNG](https://i.loli.net/2018/06/22/5b2cce9c416f7.png)
